export const CASES_LIST_REQUEST = "CASES_LIST_REQUEST";
export const CASES_LIST_SUCCESS = "CASES_LIST_SUCCESS";
export const CASES_LIST_FAIL = "CASES_LIST_FAIL";

export const CASE_DETAILS_REQUEST = "CASE_DETAILS_REQUEST";
export const CASE_DETAILS_SUCCESS = "CASE_DETAILS_SUCCESS";
export const CASE_DETAILS_FAIL = "CASE_DETAILS_FAIL";
